[phases.setup]
nixPkgs = ['python310']

[phases.install]
cmds = [
  'python -m venv /opt/venv',
  '. /opt/venv/bin/activate',
  'pip install --upgrade pip',
  'pip install -r requirements.txt'
]

[start]
cmd = 'gunicorn wsgi:app'

[build]
buildPhase = 'true'