[phases.setup]
nixPkgs = ['python312']

[phases.install]
cmds = [
  'python -m venv /opt/venv',
  '. /opt/venv/bin/activate',
  'python -m pip install --upgrade pip',
  'pip install -r requirements.txt'
]

[start]
cmd = 'bash start.sh'

[build]
buildPhase = 'true'

[variables]
PYTHONUNBUFFERED = "1"